export const CREATE_PATIENT_REQUEST = "CREATE_PATIENT_REQUEST";
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const CREATE_PATIENT_ERROR = "CREATE_PATIENT_ERROR";
export const CREATE_PATIENT_RESET = "CREATE_PATIENT_RESET";