export const GET_APPOINTMENTS_REQUEST = "GET_APPOINTMENTS_REQUEST";
export const GET_APPOINTMENTS_SUCCESS = "GET_APPOINTMENTS_SUCCESS";
export const GET_APPOINTMENTS_ERROR = "GET_APPOINTMENTS_ERROR";
export const GET_APPOINTMENTS_RESET = "GET_APPOINTMENTS_RESET";