export const GET_PATIENTS_REQUEST = "GET_PATIENTS_REQUEST";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_ERROR = "GET_PATIENTS_ERROR";
export const GET_PATIENTS_RESET = "GET_PATIENTS_RESET";